import postgres from "postgres";
import { drizzle } from "drizzle-orm/postgres-js";
import { countries, cities, events } from "../src/lib/db/schema";
import { SEED_COUNTRIES, SEED_CITIES } from "../src/lib/db/seed-data";
import slugify from "slugify";

const client = postgres(process.env.DATABASE_URL!);
const db = drizzle(client);

const COUNTRIES = [...SEED_COUNTRIES];
const CITIES = [...SEED_CITIES];

// Real European tech events, April–October 2026
const SAMPLE_EVENTS = [
  // ── Data Science & Python ─────────────────────────────────────────
  {
    title: "PyCon DE & PyData 2026",
    description: "Germany's largest Python conference combining PyCon DE and PyData. Four days of talks, tutorials, and sprints covering data science, machine learning, and Python development.",
    shortDescription: "Germany's largest Python conference with data science focus.",
    category: "data_science" as const,
    eventType: "conference" as const,
    size: "large" as const,
    startsAt: new Date("2026-04-14T09:00:00+02:00"),
    endsAt: new Date("2026-04-17T17:00:00+02:00"),
    timezone: "Europe/Berlin",
    isMultiDay: true,
    citySlug: "darmstadt",
    venueName: "darmstadtium",
    isFree: false,
    priceFrom: 100,
    priceTo: 400,
    websiteUrl: "https://pycon.de",
    registrationUrl: "https://pycon.de/tickets",
    organizerName: "Python Software Verband e.V.",
    source: "manual" as const,
  },
  {
    title: "Data Innovation Summit 2026",
    description: "Scandinavia's premier data and AI conference. Two days of cutting-edge talks on MLOps, data engineering, generative AI, and analytics leadership.",
    shortDescription: "Scandinavia's premier data and AI conference.",
    category: "data_science" as const,
    eventType: "conference" as const,
    size: "large" as const,
    startsAt: new Date("2026-05-06T08:30:00+02:00"),
    endsAt: new Date("2026-05-08T17:00:00+02:00"),
    timezone: "Europe/Stockholm",
    isMultiDay: true,
    citySlug: "stockholm",
    venueName: "Kistamässan",
    isFree: false,
    priceFrom: 600,
    priceTo: 1800,
    websiteUrl: "https://datainnovationsummit.com",
    registrationUrl: "https://datainnovationsummit.com/register",
    organizerName: "Hyperight",
    source: "manual" as const,
  },
  {
    title: "PyData Amsterdam 2026",
    description: "Community-driven conference for the PyData community. Two days of talks and workshops on Python tools for data analysis, machine learning, and visualization.",
    shortDescription: "Community PyData conference in Amsterdam.",
    category: "data_science" as const,
    eventType: "conference" as const,
    size: "medium" as const,
    startsAt: new Date("2026-09-10T09:00:00+02:00"),
    endsAt: new Date("2026-09-11T18:00:00+02:00"),
    timezone: "Europe/Amsterdam",
    isMultiDay: true,
    citySlug: "amsterdam",
    venueName: "Kromhouthal",
    isFree: false,
    priceFrom: 150,
    priceTo: 350,
    websiteUrl: "https://amsterdam.pydata.org",
    organizerName: "NumFOCUS / PyData",
    source: "manual" as const,
  },

  // ── Blockchain / Web3 ─────────────────────────────────────────────
  {
    title: "EthCC 2026",
    description: "The largest annual European Ethereum conference. Four days of talks, workshops, and side events covering L2s, DeFi, governance, and the Ethereum roadmap.",
    shortDescription: "Europe's largest Ethereum community conference.",
    category: "blockchain_web3" as const,
    eventType: "conference" as const,
    size: "large" as const,
    startsAt: new Date("2026-03-30T09:00:00+02:00"),
    endsAt: new Date("2026-04-02T18:00:00+02:00"),
    timezone: "Europe/Paris",
    isMultiDay: true,
    citySlug: "cannes",
    venueName: "Palais des Festivals",
    isFree: false,
    priceFrom: 99,
    priceTo: 599,
    websiteUrl: "https://ethcc.io",
    registrationUrl: "https://ethcc.io/tickets",
    organizerName: "Ethereum France",
    source: "manual" as const,
  },
  {
    title: "Paris Blockchain Week 2026",
    description: "Two days at the Carrousel du Louvre exploring DeFi, NFTs, regulation, and institutional crypto adoption across 300+ speakers.",
    shortDescription: "Flagship blockchain summit at the Louvre, Paris.",
    category: "blockchain_web3" as const,
    eventType: "conference" as const,
    size: "large" as const,
    startsAt: new Date("2026-04-15T09:00:00+02:00"),
    endsAt: new Date("2026-04-16T18:00:00+02:00"),
    timezone: "Europe/Paris",
    isMultiDay: true,
    citySlug: "paris",
    venueName: "Carrousel du Louvre",
    isFree: false,
    priceFrom: 199,
    priceTo: 1999,
    websiteUrl: "https://parisblockchainweek.com",
    registrationUrl: "https://parisblockchainweek.com/tickets",
    organizerName: "Paris Blockchain Week",
    source: "manual" as const,
  },
  {
    title: "European Blockchain Convention 2026",
    description: "6,000+ attendees gathering in Barcelona for Europe's leading blockchain event. Panels on regulation, institutional DeFi, tokenisation, and Web3 infrastructure.",
    shortDescription: "Europe's leading blockchain convention in Barcelona.",
    category: "blockchain_web3" as const,
    eventType: "conference" as const,
    size: "large" as const,
    startsAt: new Date("2026-09-16T09:00:00+02:00"),
    endsAt: new Date("2026-09-17T18:00:00+02:00"),
    timezone: "Europe/Madrid",
    isMultiDay: true,
    citySlug: "barcelona",
    venueName: "Fira Barcelona Montjuïc",
    isFree: false,
    priceFrom: 299,
    priceTo: 1499,
    websiteUrl: "https://eblockchainconvention.com",
    registrationUrl: "https://eblockchainconvention.com/tickets",
    organizerName: "European Blockchain Convention",
    source: "manual" as const,
  },

  // ── General Tech / Developer ──────────────────────────────────────
  {
    title: "Devoxx France 2026",
    description: "The premier French-language developer conference. Three days of Java, cloud, architecture, and software craftsmanship talks at the Palais des Congrès.",
    shortDescription: "Premier French developer conference in Paris.",
    category: "general_tech" as const,
    eventType: "conference" as const,
    size: "large" as const,
    startsAt: new Date("2026-04-22T09:00:00+02:00"),
    endsAt: new Date("2026-04-24T18:00:00+02:00"),
    timezone: "Europe/Paris",
    isMultiDay: true,
    citySlug: "paris",
    venueName: "Palais des Congrès de Paris",
    isFree: false,
    priceFrom: 250,
    priceTo: 750,
    websiteUrl: "https://www.devoxx.fr",
    registrationUrl: "https://www.devoxx.fr/register",
    organizerName: "Devoxx France",
    source: "manual" as const,
  },
  {
    title: "VivaTech 2026",
    description: "Europe's biggest startup and tech event with 150,000+ attendees. Four days of innovation showcases, startup pitches, and keynotes from global tech leaders.",
    shortDescription: "Europe's biggest startup and tech event in Paris.",
    category: "startup" as const,
    eventType: "conference" as const,
    size: "major" as const,
    startsAt: new Date("2026-06-17T09:00:00+02:00"),
    endsAt: new Date("2026-06-20T18:00:00+02:00"),
    timezone: "Europe/Paris",
    isMultiDay: true,
    citySlug: "paris",
    venueName: "Paris Expo Porte de Versailles",
    isFree: false,
    priceFrom: 50,
    priceTo: 600,
    websiteUrl: "https://vivatechnology.com",
    registrationUrl: "https://vivatechnology.com/tickets",
    organizerName: "VivaTech",
    source: "manual" as const,
  },
  {
    title: "Devoxx Poland 2026",
    description: "Central Europe's top developer conference. Three days of deep-dive talks on JVM, cloud-native, AI/ML, and modern software architecture in Krakow.",
    shortDescription: "Central Europe's top developer conference in Krakow.",
    category: "general_tech" as const,
    eventType: "conference" as const,
    size: "large" as const,
    startsAt: new Date("2026-06-17T09:00:00+02:00"),
    endsAt: new Date("2026-06-19T18:00:00+02:00"),
    timezone: "Europe/Warsaw",
    isMultiDay: true,
    citySlug: "krakow",
    venueName: "ICE Kraków Congress Centre",
    isFree: false,
    priceFrom: 200,
    priceTo: 600,
    websiteUrl: "https://devoxx.pl",
    registrationUrl: "https://devoxx.pl/tickets",
    organizerName: "Devoxx Poland",
    source: "manual" as const,
  },
  {
    title: "WeAreDevelopers World Congress 2026",
    description: "One of Europe's largest developer conferences with 15,000+ attendees. Three days of talks spanning frontend, backend, AI, DevOps, and career growth.",
    shortDescription: "Europe's largest developer conference in Berlin.",
    category: "general_tech" as const,
    eventType: "conference" as const,
    size: "major" as const,
    startsAt: new Date("2026-07-08T09:00:00+02:00"),
    endsAt: new Date("2026-07-10T18:00:00+02:00"),
    timezone: "Europe/Berlin",
    isMultiDay: true,
    citySlug: "berlin",
    venueName: "CityCube Berlin",
    isFree: false,
    priceFrom: 199,
    priceTo: 999,
    websiteUrl: "https://www.wearedevelopers.com/world-congress",
    registrationUrl: "https://www.wearedevelopers.com/world-congress/tickets",
    organizerName: "WeAreDevelopers",
    source: "manual" as const,
  },
  {
    title: "Devoxx Belgium 2026",
    description: "The original Devoxx — five days of Java, Kotlin, cloud, and developer experience talks in Antwerp. Europe's favourite developer conference.",
    shortDescription: "The original Devoxx developer conference in Antwerp.",
    category: "general_tech" as const,
    eventType: "conference" as const,
    size: "large" as const,
    startsAt: new Date("2026-10-05T09:00:00+02:00"),
    endsAt: new Date("2026-10-09T17:00:00+02:00"),
    timezone: "Europe/Brussels",
    isMultiDay: true,
    citySlug: "antwerp",
    venueName: "Kinepolis Antwerp",
    isFree: false,
    priceFrom: 400,
    priceTo: 900,
    websiteUrl: "https://devoxx.be",
    registrationUrl: "https://devoxx.be/tickets",
    organizerName: "Devoxx Belgium",
    source: "manual" as const,
  },

  // ── Cloud / DevOps ────────────────────────────────────────────────
  {
    title: "AWS Summit Paris 2026",
    description: "Free one-day cloud conference by AWS. Keynotes, breakout sessions, and hands-on labs covering serverless, containers, AI/ML, and cloud architecture.",
    shortDescription: "Free AWS cloud conference in Paris.",
    category: "cloud_infra" as const,
    eventType: "conference" as const,
    size: "large" as const,
    startsAt: new Date("2026-04-01T08:00:00+02:00"),
    endsAt: new Date("2026-04-01T18:00:00+02:00"),
    timezone: "Europe/Paris",
    isMultiDay: false,
    citySlug: "paris",
    venueName: "Palais des Congrès de Paris",
    isFree: true,
    websiteUrl: "https://aws.amazon.com/events/summits/emea/paris/",
    registrationUrl: "https://aws.amazon.com/events/summits/emea/paris/",
    organizerName: "Amazon Web Services",
    source: "manual" as const,
  },
  {
    title: "AWS Summit London 2026",
    description: "Free one-day cloud conference by AWS. Technical sessions, demos, and partner expo covering the latest in cloud computing.",
    shortDescription: "Free AWS cloud conference in London.",
    category: "cloud_infra" as const,
    eventType: "conference" as const,
    size: "large" as const,
    startsAt: new Date("2026-04-22T08:00:00+01:00"),
    endsAt: new Date("2026-04-22T18:00:00+01:00"),
    timezone: "Europe/London",
    isMultiDay: false,
    citySlug: "london",
    venueName: "ExCeL London",
    isFree: true,
    websiteUrl: "https://aws.amazon.com/events/summits/emea/london/",
    registrationUrl: "https://aws.amazon.com/events/summits/emea/london/",
    organizerName: "Amazon Web Services",
    source: "manual" as const,
  },
  {
    title: "AWS Summit Amsterdam 2026",
    description: "Free one-day AWS cloud event for the Benelux region. Sessions on AI, security, modern applications, and migration strategies.",
    shortDescription: "Free AWS cloud conference in Amsterdam.",
    category: "cloud_infra" as const,
    eventType: "conference" as const,
    size: "large" as const,
    startsAt: new Date("2026-05-27T08:00:00+02:00"),
    endsAt: new Date("2026-05-27T18:00:00+02:00"),
    timezone: "Europe/Amsterdam",
    isMultiDay: false,
    citySlug: "amsterdam",
    venueName: "RAI Amsterdam",
    isFree: true,
    websiteUrl: "https://aws.amazon.com/events/summits/emea/amsterdam/",
    organizerName: "Amazon Web Services",
    source: "manual" as const,
  },

  // ── AI / ML ───────────────────────────────────────────────────────
  {
    title: "AI Summit London 2026",
    description: "Enterprise AI conference with 5,000+ attendees. Two days of case studies, panels, and demos on applied AI, LLMs, computer vision, and AI strategy.",
    shortDescription: "Enterprise AI conference in London.",
    category: "ai_ml" as const,
    eventType: "conference" as const,
    size: "large" as const,
    startsAt: new Date("2026-06-10T09:00:00+01:00"),
    endsAt: new Date("2026-06-11T17:30:00+01:00"),
    timezone: "Europe/London",
    isMultiDay: true,
    citySlug: "london",
    venueName: "ExCeL London",
    isFree: false,
    priceFrom: 499,
    priceTo: 1999,
    websiteUrl: "https://london.theaisummit.com",
    registrationUrl: "https://london.theaisummit.com/register",
    organizerName: "Informa Tech",
    source: "manual" as const,
  },

  // ── Cybersecurity ─────────────────────────────────────────────────
  {
    title: "BSides Prague 2026",
    description: "Community-driven information security conference. Two days of talks, workshops, and CTF challenges in a relaxed, inclusive atmosphere.",
    shortDescription: "Community infosec conference in Prague.",
    category: "cybersecurity" as const,
    eventType: "conference" as const,
    size: "small" as const,
    startsAt: new Date("2026-04-23T09:00:00+02:00"),
    endsAt: new Date("2026-04-24T18:00:00+02:00"),
    timezone: "Europe/Prague",
    isMultiDay: true,
    citySlug: "prague",
    venueName: "Prague Congress Centre",
    isFree: false,
    priceFrom: 20,
    priceTo: 50,
    websiteUrl: "https://bsidesprg.cz",
    organizerName: "BSides Prague",
    source: "manual" as const,
  },
  {
    title: "BSides Budapest 2026",
    description: "One-day community security conference with talks on offensive security, threat intelligence, and incident response.",
    shortDescription: "Community security conference in Budapest.",
    category: "cybersecurity" as const,
    eventType: "conference" as const,
    size: "small" as const,
    startsAt: new Date("2026-04-29T09:00:00+02:00"),
    endsAt: new Date("2026-04-29T18:00:00+02:00"),
    timezone: "Europe/Budapest",
    isMultiDay: false,
    citySlug: "budapest",
    venueName: "Budapest Congress Center",
    isFree: false,
    priceFrom: 15,
    priceTo: 40,
    websiteUrl: "https://bsidesbud.com",
    organizerName: "BSides Budapest",
    source: "manual" as const,
  },

  // ── Hacker / Maker / Community ────────────────────────────────────
  {
    title: "GPN24 — Gulaschprogrammiernacht",
    description: "Annual hacker camp by Entropia (CCC Karlsruhe). Four days of talks, workshops, and creative hacking in the ZKM. Soldering, CTF, retro computing, and late-night coding.",
    shortDescription: "CCC Karlsruhe's annual hacker camp at ZKM.",
    category: "hacker_maker_community" as const,
    eventType: "conference" as const,
    size: "medium" as const,
    startsAt: new Date("2026-06-04T14:00:00+02:00"),
    endsAt: new Date("2026-06-07T14:00:00+02:00"),
    timezone: "Europe/Berlin",
    isMultiDay: true,
    citySlug: "karlsruhe",
    venueName: "ZKM — Zentrum für Kunst und Medien",
    venueAddress: "Lorenzstraße 19, 76135 Karlsruhe",
    isFree: false,
    priceFrom: 42,
    priceTo: 80,
    websiteUrl: "https://entropia.de/GPN",
    registrationUrl: "https://entropia.de/GPN",
    organizerName: "Entropia e.V. (CCC Karlsruhe)",
    source: "manual" as const,
  },
  {
    title: "Electromagnetic Field 2026",
    description: "UK's hacker camp in the countryside. Three days of talks, workshops, and installations covering hardware hacking, software, science, art, and crafts. Camping included.",
    shortDescription: "UK's beloved hacker camp in Herefordshire.",
    category: "hacker_maker_community" as const,
    eventType: "conference" as const,
    size: "large" as const,
    startsAt: new Date("2026-07-16T10:00:00+01:00"),
    endsAt: new Date("2026-07-19T16:00:00+01:00"),
    timezone: "Europe/London",
    isMultiDay: true,
    citySlug: "eastnor",
    venueName: "Eastnor Castle Deer Park",
    venueAddress: "Eastnor, Ledbury, Herefordshire HR8 1RL",
    isFree: false,
    priceFrom: 120,
    priceTo: 180,
    websiteUrl: "https://www.emfcamp.org",
    registrationUrl: "https://www.emfcamp.org/tickets",
    organizerName: "Electromagnetic Field Ltd",
    source: "manual" as const,
  },

  // ── Design / UX ───────────────────────────────────────────────────
  {
    title: "UX London 2026",
    description: "Three-day UX design conference with world-class speakers. Workshops, talks, and networking for product designers, researchers, and design leaders.",
    shortDescription: "Premier UX design conference in London.",
    category: "design_ux" as const,
    eventType: "conference" as const,
    size: "medium" as const,
    startsAt: new Date("2026-06-02T09:00:00+01:00"),
    endsAt: new Date("2026-06-04T17:30:00+01:00"),
    timezone: "Europe/London",
    isMultiDay: true,
    citySlug: "london",
    venueName: "etc.venues 155 Bishopsgate",
    isFree: false,
    priceFrom: 600,
    priceTo: 1800,
    websiteUrl: "https://uxlondon.com",
    registrationUrl: "https://uxlondon.com/tickets",
    organizerName: "Clearleft",
    source: "manual" as const,
  },
  {
    title: "Hatch Conference 2026",
    description: "Intimate design and technology conference in Berlin. Two days of curated talks on design systems, creative coding, accessibility, and inclusive design.",
    shortDescription: "Intimate design+tech conference in Berlin.",
    category: "design_ux" as const,
    eventType: "conference" as const,
    size: "small" as const,
    startsAt: new Date("2026-09-16T09:00:00+02:00"),
    endsAt: new Date("2026-09-18T17:00:00+02:00"),
    timezone: "Europe/Berlin",
    isMultiDay: true,
    citySlug: "berlin",
    venueName: "Radialsystem",
    isFree: false,
    priceFrom: 299,
    priceTo: 599,
    websiteUrl: "https://hfrb.io",
    organizerName: "Hatch",
    source: "manual" as const,
  },

  // ── FinTech ───────────────────────────────────────────────────────
  {
    title: "Money20/20 Europe 2026",
    description: "The world's leading fintech event comes to Amsterdam. 8,500+ attendees from payments, banking, and financial services discuss embedded finance, open banking, and digital identity.",
    shortDescription: "World's leading fintech event in Amsterdam.",
    category: "fintech" as const,
    eventType: "conference" as const,
    size: "major" as const,
    startsAt: new Date("2026-06-02T08:30:00+02:00"),
    endsAt: new Date("2026-06-04T18:00:00+02:00"),
    timezone: "Europe/Amsterdam",
    isMultiDay: true,
    citySlug: "amsterdam",
    venueName: "RAI Amsterdam",
    isFree: false,
    priceFrom: 1999,
    priceTo: 4999,
    websiteUrl: "https://europe.money2020.com",
    registrationUrl: "https://europe.money2020.com/register",
    organizerName: "Money20/20",
    source: "manual" as const,
  },

  // ── HealthTech ────────────────────────────────────────────────────
  {
    title: "HIMSS26 Europe",
    description: "Healthcare IT and digital health conference. Three days of sessions on health data, interoperability, AI in healthcare, and digital patient experience.",
    shortDescription: "Healthcare IT conference in Copenhagen.",
    category: "healthtech" as const,
    eventType: "conference" as const,
    size: "large" as const,
    startsAt: new Date("2026-05-19T08:30:00+02:00"),
    endsAt: new Date("2026-05-21T17:00:00+02:00"),
    timezone: "Europe/Copenhagen",
    isMultiDay: true,
    citySlug: "copenhagen",
    venueName: "Bella Center Copenhagen",
    isFree: false,
    priceFrom: 500,
    priceTo: 1500,
    websiteUrl: "https://www.himss.org/event-himss-europe",
    registrationUrl: "https://www.himss.org/event-himss-europe",
    organizerName: "HIMSS",
    source: "manual" as const,
  },

  // ── Cloud / Infrastructure (bonus) ────────────────────────────────
  // ── Meetups & Workshops ───────────────────────────────────────────
  {
    title: "Berlin AI Meetup #47",
    description: "Monthly gathering of AI practitioners in Berlin. This month: practical RAG architectures and lessons learned from production LLM systems.",
    shortDescription: "Monthly AI practitioners meetup in Berlin.",
    category: "ai_ml" as const,
    eventType: "meetup" as const,
    size: "medium" as const,
    startsAt: new Date("2026-05-14T18:30:00+02:00"),
    endsAt: new Date("2026-05-14T21:00:00+02:00"),
    timezone: "Europe/Berlin",
    isMultiDay: false,
    citySlug: "berlin",
    venueName: "Factory Berlin Görlitzer Park",
    venueAddress: "Lohmühlenstraße 65, 12435 Berlin",
    isFree: true,
    websiteUrl: "https://lu.ma/berlin-ai",
    organizerName: "Berlin AI Community",
    source: "manual" as const,
  },
  {
    title: "Amsterdam Rust Meetup",
    description: "Bi-monthly Rust language meetup. Lightning talks, live coding, and pizza. All experience levels welcome.",
    shortDescription: "Bi-monthly Rust language meetup in Amsterdam.",
    category: "devtools" as const,
    eventType: "meetup" as const,
    size: "small" as const,
    startsAt: new Date("2026-06-11T18:00:00+02:00"),
    endsAt: new Date("2026-06-11T21:00:00+02:00"),
    timezone: "Europe/Amsterdam",
    isMultiDay: false,
    citySlug: "amsterdam",
    venueName: "TQ Amsterdam",
    venueAddress: "Singel 542, 1017 AZ Amsterdam",
    isFree: true,
    websiteUrl: "https://www.meetup.com/rust-amsterdam/",
    organizerName: "Rust Amsterdam",
    source: "manual" as const,
  },
  {
    title: "Dublin Cloud Native Hands-On Workshop",
    description: "Full-day hands-on workshop on Kubernetes, service mesh, and GitOps. Bring your laptop — you'll deploy a production-grade stack by end of day.",
    shortDescription: "Hands-on Kubernetes & GitOps workshop in Dublin.",
    category: "cloud_infra" as const,
    eventType: "workshop" as const,
    size: "small" as const,
    startsAt: new Date("2026-05-09T09:30:00+01:00"),
    endsAt: new Date("2026-05-09T17:00:00+01:00"),
    timezone: "Europe/Dublin",
    isMultiDay: false,
    citySlug: "dublin",
    venueName: "Dogpatch Labs",
    venueAddress: "The CHQ Building, Custom House Quay, Dublin 1",
    isFree: false,
    priceFrom: 75,
    websiteUrl: "https://www.meetup.com/cloud-native-dublin/",
    organizerName: "Cloud Native Dublin",
    source: "manual" as const,
  },
  {
    title: "ETHBerlin Hackathon 2026",
    description: "48-hour Ethereum hackathon in Berlin. Build decentralised apps, compete for prizes, and collaborate with 500+ developers from across Europe.",
    shortDescription: "48-hour Ethereum hackathon in Berlin.",
    category: "blockchain_web3" as const,
    eventType: "hackathon" as const,
    size: "medium" as const,
    startsAt: new Date("2026-09-25T18:00:00+02:00"),
    endsAt: new Date("2026-09-27T18:00:00+02:00"),
    timezone: "Europe/Berlin",
    isMultiDay: true,
    citySlug: "berlin",
    venueName: "Funkhaus Berlin",
    venueAddress: "Nalepastraße 18, 12459 Berlin",
    isFree: true,
    websiteUrl: "https://ethberlin.org",
    registrationUrl: "https://ethberlin.org/apply",
    organizerName: "Department of Decentralization",
    source: "manual" as const,
  },
  {
    title: "Vienna AI Safety Reading Group",
    description: "Weekly reading group discussing the latest AI alignment and safety research papers. Open to anyone interested in technical AI safety.",
    shortDescription: "Weekly AI safety reading group in Vienna.",
    category: "ai_ml" as const,
    eventType: "meetup" as const,
    size: "small" as const,
    startsAt: new Date("2026-05-06T18:00:00+02:00"),
    endsAt: new Date("2026-05-06T20:00:00+02:00"),
    timezone: "Europe/Vienna",
    isMultiDay: false,
    citySlug: "vienna",
    venueName: "Metalab",
    venueAddress: "Rathausstraße 6, 1010 Wien",
    isFree: true,
    websiteUrl: "https://metalab.at",
    organizerName: "Vienna AI Safety",
    source: "manual" as const,
  },

  // ── Startup ───────────────────────────────────────────────────────
  {
    title: "EU-Startups Summit 2026",
    description: "Annual flagship event bringing together 2,500 founders, VCs, angels, and corporates in Malta. Pitch competitions, fireside chats, and startup expo.",
    shortDescription: "Europe's flagship startup summit in Malta.",
    category: "startup" as const,
    eventType: "conference" as const,
    size: "large" as const,
    startsAt: new Date("2026-05-07T09:00:00+02:00"),
    endsAt: new Date("2026-05-08T18:00:00+02:00"),
    timezone: "Europe/Malta",
    isMultiDay: true,
    citySlug: "valletta",
    venueName: "Mediterranean Conference Centre",
    isFree: false,
    priceFrom: 149,
    priceTo: 599,
    websiteUrl: "https://www.eu-startups.com/summit/",
    registrationUrl: "https://www.eu-startups.com/summit/tickets/",
    organizerName: "EU-Startups",
    source: "manual" as const,
  },
  {
    title: "Latitude59 2026",
    description: "Tallinn's flagship startup and tech event in the world's first digital society. Two days of keynotes, investor matchmaking, and startup pitches with 800+ investors.",
    shortDescription: "Estonia's flagship startup and tech event.",
    category: "startup" as const,
    eventType: "conference" as const,
    size: "large" as const,
    startsAt: new Date("2026-05-21T09:00:00+03:00"),
    endsAt: new Date("2026-05-22T18:00:00+03:00"),
    timezone: "Europe/Tallinn",
    isMultiDay: true,
    citySlug: "tallinn",
    venueName: "Kultuurikatel",
    isFree: false,
    priceFrom: 199,
    priceTo: 799,
    websiteUrl: "https://latitude59.ee",
    registrationUrl: "https://latitude59.ee/tickets",
    organizerName: "Latitude59",
    source: "manual" as const,
  },
  {
    title: "TNW Conference 2026",
    description: "Amsterdam's iconic tech festival with 8,000+ attendees. Two days of talks, networking, and demos from startups, scaleups, and global tech leaders.",
    shortDescription: "Amsterdam's iconic tech and startup festival.",
    category: "startup" as const,
    eventType: "conference" as const,
    size: "large" as const,
    startsAt: new Date("2026-05-27T09:00:00+02:00"),
    endsAt: new Date("2026-05-28T18:00:00+02:00"),
    timezone: "Europe/Amsterdam",
    isMultiDay: true,
    citySlug: "amsterdam",
    venueName: "NDSM Wharf",
    isFree: false,
    priceFrom: 399,
    priceTo: 1299,
    websiteUrl: "https://thenextweb.com/conference",
    registrationUrl: "https://thenextweb.com/conference/tickets",
    organizerName: "TNW (The Next Web)",
    source: "manual" as const,
  },
  {
    title: "TechBBQ 2026",
    description: "Scandinavia's leading startup summit with 8,000+ attendees. Two days of keynotes, workshops, investor meetings, and a vibrant startup expo in Copenhagen.",
    shortDescription: "Scandinavia's leading startup summit in Copenhagen.",
    category: "startup" as const,
    eventType: "conference" as const,
    size: "large" as const,
    startsAt: new Date("2026-08-26T08:30:00+02:00"),
    endsAt: new Date("2026-08-27T18:00:00+02:00"),
    timezone: "Europe/Copenhagen",
    isMultiDay: true,
    citySlug: "copenhagen",
    venueName: "Øksnehallen",
    isFree: false,
    priceFrom: 199,
    priceTo: 899,
    websiteUrl: "https://techbbq.dk",
    registrationUrl: "https://techbbq.dk/tickets",
    organizerName: "TechBBQ",
    source: "manual" as const,
  },
  {
    title: "Bits & Pretzels 2026",
    description: "Europe's iconic founders festival during Munich Oktoberfest. Three days of talks, networking, and startup pitches with 7,500 entrepreneurs, investors, and tech leaders.",
    shortDescription: "Europe's iconic founders festival at Oktoberfest.",
    category: "startup" as const,
    eventType: "conference" as const,
    size: "large" as const,
    startsAt: new Date("2026-09-27T09:00:00+02:00"),
    endsAt: new Date("2026-09-29T20:00:00+02:00"),
    timezone: "Europe/Berlin",
    isMultiDay: true,
    citySlug: "munich",
    venueName: "ICM Munich",
    isFree: false,
    priceFrom: 599,
    priceTo: 2999,
    websiteUrl: "https://www.bitsandpretzels.com",
    registrationUrl: "https://www.bitsandpretzels.com/tickets",
    organizerName: "Bits & Pretzels",
    source: "manual" as const,
  },
];

async function seed() {
  console.log("🌱 Seeding database...");

  // Insert countries
  console.log("  → Countries...");
  await db
    .insert(countries)
    .values(COUNTRIES)
    .onConflictDoNothing();
  const allCountries = await db.select().from(countries);
  console.log(`    ✓ ${allCountries.length} countries`);

  // Build country code → id map
  const countryMap = new Map(allCountries.map((c) => [c.code, c.id]));

  // Insert cities
  console.log("  → Cities...");
  const cityValues = CITIES.map((c) => ({
    name: c.name,
    slug: slugify(c.name, { lower: true, strict: true }),
    countryId: countryMap.get(c.countryCode)!,
    latitude: c.lat,
    longitude: c.lng,
    location: [c.lng, c.lat] as [number, number], // PostGIS: [lng, lat]
    timezone: c.tz,
    isPopular: c.popular,
  }));

  await db
    .insert(cities)
    .values(cityValues)
    .onConflictDoNothing();
  const allCities = await db.select().from(cities);
  console.log(`    ✓ ${allCities.length} cities`);

  // Build city slug → data map
  const cityMap = new Map(allCities.map((c) => [c.slug, c]));

  // Insert sample events
  console.log("  → Sample events...");
  let eventCount = 0;
  for (const evt of SAMPLE_EVENTS) {
    const city = cityMap.get(evt.citySlug);
    if (!city) {
      console.warn(`    ⚠ City not found: ${evt.citySlug}, skipping ${evt.title}`);
      continue;
    }
    const country = allCountries.find((c) => c.id === city.countryId);

    await db.insert(events).values({
      title: evt.title,
      slug: slugify(evt.title, { lower: true, strict: true }),
      description: evt.description,
      shortDescription: evt.shortDescription,
      category: evt.category,
      eventType: evt.eventType,
      size: evt.size,
      startsAt: evt.startsAt,
      endsAt: evt.endsAt ?? null,
      timezone: evt.timezone,
      isMultiDay: evt.isMultiDay,
      cityId: city.id,
      countryId: country?.id ?? null,
      venueName: evt.venueName ?? null,
      venueAddress: evt.venueAddress ?? null,
      latitude: city.latitude,
      longitude: city.longitude,
      location: [city.longitude, city.latitude] as [number, number],
      isFree: evt.isFree,
      priceFrom: evt.priceFrom ?? null,
      priceTo: evt.priceTo ?? null,
      websiteUrl: evt.websiteUrl ?? null,
      registrationUrl: evt.registrationUrl ?? null,
      organizerName: evt.organizerName ?? null,
      source: evt.source,
      status: "approved",
    }).onConflictDoNothing();
    eventCount++;
  }
  console.log(`    ✓ ${eventCount} events`);

  console.log("✅ Seed complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
